services:
  - type: web
    name: gym-management
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn gym_management.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gym-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "*" # You should update this to your specific .onrender.com domain later
      - key: JWT_ACCESS_TOKEN_LIFETIME
        value: "60"
      - key: JWT_REFRESH_TOKEN_LIFETIME
        value: "7"
      - key: TWILIO_ACCOUNT_SID
        value: "" # Fill these in Render Dashboard
      - key: TWILIO_AUTH_TOKEN
        value: ""
      - key: TWILIO_WHATSAPP_NUMBER
        value: "whatsapp:+14155238886"

databases:
  - name: gym-db
    plan: free
